/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/

'use strict';

var obsidian = require('obsidian');

/*! *****************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */

function __awaiter(thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
}

function generateId() {
    return Math.random().toString(36).substr(2, 6);
}
const illegalHeadingCharsRegex = /[!"#$%&()*+,.:;<=>?@^`{|}~\/\[\]\\]/g;
function sanitizeHeading(heading) {
    return heading
        .replace(illegalHeadingCharsRegex, " ")
        .replace(/\s+/g, " ")
        .trim();
}
function shouldInsertAfter(block) {
    if (block.type) {
        return [
            "blockquote",
            "code",
            "table",
            "comment",
            "footnoteDefinition",
        ].includes(block.type);
    }
}
class MyPlugin extends obsidian.Plugin {
    onload() {
        return __awaiter(this, void 0, void 0, function* () {
            this.registerEvent(this.app.workspace.on("editor-menu", (menu, editor, view) => {
                const block = this.getBlock(editor, view.file);
                if (!block)
                    return;
                const isHeading = !!block.heading;
                const onClick = (isEmbed) => {
                    if (isHeading) {
                        this.handleHeading(view.file, block, isEmbed);
                    }
                    else {
                        this.handleBlock(view.file, editor, block, isEmbed);
                    }
                };
                menu.addItem((item) => {
                    item
                        .setTitle(isHeading ? "Copy link to heading" : "Copy link to block")
                        .setIcon("links-coming-in")
                        .onClick(() => onClick(false));
                });
                menu.addItem((item) => {
                    item
                        .setTitle(isHeading ? "Copy heading embed" : "Copy block embed")
                        .setIcon("links-coming-in")
                        .onClick(() => onClick(true));
                });
            }));
            this.addCommand({
                id: "copy-link-to-block",
                name: "Copy link to current block or heading",
                editorCheckCallback: (isChecking, editor, view) => {
                    return this.handleCommand(isChecking, editor, view, false);
                },
            });
            this.addCommand({
                id: "copy-embed-to-block",
                name: "Copy embed to current block or heading",
                editorCheckCallback: (isChecking, editor, view) => {
                    return this.handleCommand(isChecking, editor, view, true);
                },
            });
        });
    }
    handleCommand(isChecking, editor, view, isEmbed) {
        if (isChecking) {
            return !!this.getBlock(editor, view.file);
        }
        const block = this.getBlock(editor, view.file);
        if (!block)
            return;
        const isHeading = !!block.heading;
        if (isHeading) {
            this.handleHeading(view.file, block, isEmbed);
        }
        else {
            this.handleBlock(view.file, editor, block, isEmbed);
        }
    }
    getBlock(editor, file) {
        const cursor = editor.getCursor("to");
        const fileCache = this.app.metadataCache.getFileCache(file);
        let block = ((fileCache === null || fileCache === void 0 ? void 0 : fileCache.sections) || []).find((section) => {
            return (section.position.start.line <= cursor.line &&
                section.position.end.line >= cursor.line);
        });
        if ((block === null || block === void 0 ? void 0 : block.type) === "list") {
            block = ((fileCache === null || fileCache === void 0 ? void 0 : fileCache.listItems) || []).find((item) => {
                return (item.position.start.line <= cursor.line &&
                    item.position.end.line >= cursor.line);
            });
        }
        else if ((block === null || block === void 0 ? void 0 : block.type) === "heading") {
            block = fileCache.headings.find((heading) => {
                return heading.position.start.line === block.position.start.line;
            });
        }
        return block;
    }
    handleHeading(file, block, isEmbed) {
        navigator.clipboard.writeText(`${isEmbed ? "!" : ""}${this.app.fileManager.generateMarkdownLink(file, "", "#" + sanitizeHeading(block.heading))}`);
    }
    handleBlock(file, editor, block, isEmbed) {
        const blockId = block.id;
        // Copy existing block id
        if (blockId) {
            return navigator.clipboard.writeText(`${isEmbed ? "!" : ""}${this.app.fileManager.generateMarkdownLink(file, "", "#^" + blockId)}`);
        }
        // Add a block id
        const sectionEnd = block.position.end;
        const end = {
            ch: sectionEnd.col,
            line: sectionEnd.line,
        };
        const id = generateId();
        const spacer = shouldInsertAfter(block) ? "\n\n" : " ";
        editor.replaceRange(`${spacer}^${id}`, end);
        navigator.clipboard.writeText(`${isEmbed ? "!" : ""}${this.app.fileManager.generateMarkdownLink(file, "", "#^" + id)}`);
    }
}

module.exports = MyPlugin;


/* nosourcemap */